#!/usr/bin/env python
"""Generate markdown reference pages under docs/reference/ from library introspection.

Usage:
    uv run python scripts/generate_reference.py            # write pages
    uv run python scripts/generate_reference.py --check    # CI drift gate

The pages are regenerated from the library's own registries and typed
structures so they cannot drift from the code:

- selectors.md            selector vocabulary (pseudo-classes, attribute operators)
- engines.md              engines per capability from the engine registry
- installation-extras.md  optional dependency groups from utils.optional_imports
- exceptions.md           exception hierarchy from natural_pdf.exceptions
- ocr-options.md          per-engine OCR option tables from ocr.ocr_options

Descriptions the registries do not carry are curated in the maps below. The
generator fails loudly when a registered name has no curated description (or a
curated name is no longer registered) — that is the drift guard. Every curated
example selector must also parse via ``natural_pdf.selectors.parser``.

Isolation: the registries this script introspects are mutable process globals
(selector clauses, the engine provider, the unified OCR dispatch table).
Anything imported earlier in the same interpreter — a test suite that registers
throwaway engines, a third-party package that self-registers on import — would
otherwise leak into the output. ``main()`` therefore never introspects in the
current process: it re-invokes this script with ``--introspect-json`` in a
fresh subprocess and uses what a clean ``import natural_pdf`` sees.

Third-party plugin policy: the generated pages document BUILT-IN registrations
only. The introspection subprocess filters the ``natural_pdf.engines``
entry-point group before importing the library, so installed plugins never
appear (and cannot make the CI drift gate flap across environments). The
affected pages say so in their intro text.
"""

from __future__ import annotations

import argparse
import ast
import dataclasses
import inspect
import json
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_OUTPUT_DIR = REPO_ROOT / "docs" / "reference"

HEADER_COMMENT = "<!-- GENERATED by scripts/generate_reference.py — do not edit -->"
INTROSPECTION_TIMEOUT_SECONDS = 120


class ReferenceGenerationError(RuntimeError):
    """Raised when introspection and the curated maps disagree."""


# ---------------------------------------------------------------------------
# Markdown helpers
# ---------------------------------------------------------------------------


def _md_escape(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _md_table(headers: Sequence[str], rows: Iterable[Sequence[str]]) -> str:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_md_escape(cell) for cell in row) + " |")
    return "\n".join(lines)


def _page(title: str, intro: str, body: str) -> str:
    parts = [HEADER_COMMENT, "", f"# {title}", ""]
    if intro:
        parts.extend([intro.strip(), ""])
    parts.append(body.strip())
    return "\n".join(parts) + "\n"


def _code(text: str) -> str:
    return f"`{text}`"


# ---------------------------------------------------------------------------
# Curated descriptions (drift-guarded against the live registries)
# ---------------------------------------------------------------------------

# canonical name -> tuple of registered aliases
PSEUDO_ALIASES: Dict[str, Tuple[str, ...]] = {
    "startswith": ("starts-with",),
    "endswith": ("ends-with",),
    "strike": ("strikethrough", "strikeout"),
    "underline": ("underlined",),
    "highlight": ("highlighted",),
}

# canonical element-filter pseudo-class -> (what it matches, example)
PSEUDO_DESCRIPTIONS: Dict[str, Tuple[str, str]] = {
    "bold": ("Text drawn with a bold font variant.", "text:bold"),
    "italic": ("Text drawn with an italic font variant.", "text:italic"),
    "not-bold": ("Text that is not bold.", "text:not-bold"),
    "not-italic": ("Text that is not italic.", "text:not-italic"),
    "contains": (
        "Element text contains the given string. Case-sensitive by default; "
        "pass `case=False` to `find`/`find_all` for case-insensitive, "
        "`regex=True` to treat the argument as a regular expression.",
        'text:contains("Invoice")',
    ),
    "regex": (
        "Element text matches the regular expression (via `re.search`). "
        "`case=False` adds `re.IGNORECASE`.",
        'text:regex("\\d{4}-\\d{2}")',
    ),
    "startswith": ("Element text starts with the given string.", 'text:startswith("Total")'),
    "endswith": ("Element text ends with the given string.", 'text:endswith("%")'),
    "empty": ("Element has no text, or only whitespace.", "text:empty"),
    "not-empty": ("Element has non-whitespace text.", "text:not-empty"),
    "first-child": ("Element is the first child of its parent.", "text:first-child"),
    "last-child": ("Element is the last child of its parent.", "text:last-child"),
    "horizontal": ("Element reports `is_horizontal` (mainly lines).", "line:horizontal"),
    "vertical": ("Element reports `is_vertical` (mainly lines).", "line:vertical"),
    "checked": ("Checkbox-like element whose `is_checked` is true.", "checkbox:checked"),
    "unchecked": ("Checkbox-like element whose `is_checked` is false.", "checkbox:unchecked"),
    "strike": ("Text with strikethrough decoration.", "text:strike"),
    "underline": ("Text with underline decoration.", "text:underline"),
    "highlight": ("Text covered by a highlight annotation.", "text:highlight"),
}

# collection-level (post) pseudo-class -> (what it does, example)
POST_PSEUDO_DESCRIPTIONS: Dict[str, Tuple[str, str]] = {
    "first": ("Keep only the first matched element.", "text:bold:first"),
    "last": ("Keep only the last matched element.", "text:bold:last"),
    "nth": (
        "Keep the element at the given 0-based index; negative indices count from the end.",
        "text:nth(2)",
    ),
    "slice": (
        "Slice the matches with Python slice semantics: `:slice(stop)`, "
        "`:slice(start, stop)`, or `:slice(start, stop, step)`.",
        "text:slice(0, 5)",
    ),
    "limit": ("Keep at most the first N matches.", "text:limit(10)"),
}

# relational pseudo-class -> (what it does, example)
RELATIONAL_PSEUDO_DESCRIPTIONS: Dict[str, Tuple[str, str]] = {
    "above": (
        "Keep elements entirely above the first element matched by the reference selector.",
        "text:above(line:horizontal)",
    ),
    "below": (
        "Keep elements entirely below the first element matched by the reference selector.",
        'text:below(text:contains("Header"))',
    ),
    "left-of": (
        "Keep elements entirely left of the first element matched by the reference selector.",
        "text:left-of(rect)",
    ),
    "right-of": (
        "Keep elements entirely right of the first element matched by the reference selector.",
        "text:right-of(rect)",
    ),
    "near": (
        "Keep elements whose center is within `near_threshold` points (default 50) of the "
        "reference element's center.",
        'text:near(text:contains("Total"))',
    ),
}

# parser-level pseudo-classes (handled by dispatch tables in selectors/parser.py)
PARSER_PSEUDO_DESCRIPTIONS: Dict[str, Tuple[str, str]] = {
    "not": ("Invert an inner selector.", "text:not(:bold)"),
    "closest": (
        "Rank matches by text similarity to the argument; `@threshold` sets the minimum "
        "similarity (0-1). Applied during selector execution.",
        "text:closest(Invoice Number@0.7)",
    ),
    "ocr": (
        "OCR-tolerant text match that forgives commonly-confused characters "
        "(handled during selector execution).",
        'text:ocr("Invoice")',
    ),
}

# attribute operator -> (meaning, example)
ATTRIBUTE_OP_DESCRIPTIONS: Dict[str, Tuple[str, str]] = {
    "=": (
        "Equal. Colors compare with a small perceptual tolerance; boolean attributes "
        "accept `true`/`false`/`1`/`0`/`yes`.",
        "text[size=12]",
    ),
    "!=": ("Not equal.", "text[fontname!=Courier]"),
    "~=": (
        "Approximately equal — colors match within a small perceptual distance "
        "(`[color~=red]` accepts near-reds). Numeric values are rejected at parse "
        "time as ambiguous; use an explicit range like `[size>=11][size<=13]`.",
        "text[color~=red]",
    ),
    "^=": ("String starts with the value.", "text[fontname^=Arial]"),
    "$=": ("String ends with the value.", "text[fontname$=Bold]"),
    "*=": (
        "String contains the value (case-insensitive for `fontname`).",
        "text[fontname*=narrow]",
    ),
    ">=": ("Numeric greater-than-or-equal.", "text[size>=14]"),
    "<=": ("Numeric less-than-or-equal.", "text[size<=8]"),
    ">": ("Numeric greater-than.", "text[size>12]"),
    "<": ("Numeric less-than.", "text[width<100]"),
}

# The bare [attr] form is handled by the parser outside _ATTRIBUTE_OP_BUILDERS.
ATTRIBUTE_EXISTS_ROW = (
    "(bare)",
    "",
    "Attribute exists and is not None.",
    "text[fontname]",
)

# Registered attribute *handlers* (extension point; none built in today).
ATTRIBUTE_HANDLER_DESCRIPTIONS: Dict[str, Tuple[str, str]] = {}


def _guard_registry_coverage(
    registry_names: Iterable[str],
    curated: Mapping[str, Tuple[str, str]],
    aliases: Mapping[str, Tuple[str, ...]],
    kind: str,
) -> None:
    """Fail loudly when the live registry and curated maps disagree."""
    registered = set(registry_names)
    alias_names = {alias for names in aliases.values() for alias in names}
    covered = set(curated) | alias_names

    missing = sorted(registered - covered)
    if missing:
        raise ReferenceGenerationError(
            f"{kind}: registered names missing a curated description in "
            f"scripts/generate_reference.py: {missing}. Add them to the curated map."
        )
    stale = sorted(set(curated) - registered)
    if stale:
        raise ReferenceGenerationError(
            f"{kind}: curated descriptions for names that are no longer registered: {stale}. "
            "Remove them from scripts/generate_reference.py."
        )
    stale_aliases = sorted(alias_names - registered)
    if stale_aliases:
        raise ReferenceGenerationError(
            f"{kind}: curated aliases that are no longer registered: {stale_aliases}."
        )
    for canonical in aliases:
        if canonical not in curated:
            raise ReferenceGenerationError(
                f"{kind}: alias group canonical name {canonical!r} has no curated description."
            )


def _iter_curated_examples() -> Iterable[Tuple[str, str]]:
    """Yield ``(origin, example_selector)`` for every curated example."""
    for kind, curated in (
        ("pseudo-classes", PSEUDO_DESCRIPTIONS),
        ("collection pseudo-classes", POST_PSEUDO_DESCRIPTIONS),
        ("relational pseudo-classes", RELATIONAL_PSEUDO_DESCRIPTIONS),
        ("parser pseudo-classes", PARSER_PSEUDO_DESCRIPTIONS),
        ("attribute operators", ATTRIBUTE_OP_DESCRIPTIONS),
        ("attribute handlers", ATTRIBUTE_HANDLER_DESCRIPTIONS),
    ):
        for name, (_desc, example) in curated.items():
            yield f"{kind} {name!r}", example
    yield "attribute operators '(bare)'", ATTRIBUTE_EXISTS_ROW[3]


def _validate_curated_examples() -> None:
    """Every example selector on the generated page must actually parse.

    Guards against documenting syntax the parser rejects (e.g. `text[size~=12]`:
    numeric ``~=`` raises at parse time by design).
    """
    from natural_pdf.selectors.parser import parse_selector

    failures: List[str] = []
    for origin, example in _iter_curated_examples():
        try:
            parse_selector(example)
        except Exception as exc:
            failures.append(f"  {origin}: {example!r} -> {exc}")
    if failures:
        raise ReferenceGenerationError(
            "curated example selectors failed to parse:\n"
            + "\n".join(failures)
            + "\nFix the examples in scripts/generate_reference.py."
        )


# ---------------------------------------------------------------------------
# Page: selectors.md
# ---------------------------------------------------------------------------


def generate_selectors_page() -> str:
    import natural_pdf.selectors  # noqa: F401  (registers built-in clauses)
    from natural_pdf.selectors import parser as selector_parser
    from natural_pdf.selectors import registry as selector_registry

    pseudo_names = set(selector_registry._PSEUDO_HANDLERS)
    post_names = set(selector_registry._POST_HANDLERS)
    relational_names = set(selector_registry._RELATIONAL_HANDLERS)
    attribute_handler_names = set(selector_registry._ATTRIBUTE_HANDLERS)
    parser_pseudo_names = set(selector_parser._PSEUDO_CLASS_BUILDERS)
    attribute_ops = set(selector_parser._ATTRIBUTE_OP_BUILDERS)

    _guard_registry_coverage(pseudo_names, PSEUDO_DESCRIPTIONS, PSEUDO_ALIASES, "pseudo-classes")
    _guard_registry_coverage(post_names, POST_PSEUDO_DESCRIPTIONS, {}, "collection pseudo-classes")
    _guard_registry_coverage(
        relational_names, RELATIONAL_PSEUDO_DESCRIPTIONS, {}, "relational pseudo-classes"
    )
    _guard_registry_coverage(
        parser_pseudo_names, PARSER_PSEUDO_DESCRIPTIONS, {}, "parser pseudo-classes"
    )
    _guard_registry_coverage(attribute_ops, ATTRIBUTE_OP_DESCRIPTIONS, {}, "attribute operators")
    _guard_registry_coverage(
        attribute_handler_names, ATTRIBUTE_HANDLER_DESCRIPTIONS, {}, "attribute handlers"
    )
    _validate_curated_examples()

    def pseudo_rows(curated: Mapping[str, Tuple[str, str]]) -> List[Tuple[str, str, str, str]]:
        rows = []
        for name in sorted(curated):
            desc, example = curated[name]
            aliases = ", ".join(_code(f":{a}") for a in PSEUDO_ALIASES.get(name, ()))
            rows.append((_code(f":{name}"), aliases, desc, _code(example)))
        return rows

    sections: List[str] = []

    sections.append("## Pseudo-classes (element filters)")
    sections.append("Applied with a colon, e.g. `text:bold`. These filter individual elements.")
    sections.append(
        _md_table(
            ["Name", "Aliases", "What it matches", "Example"], pseudo_rows(PSEUDO_DESCRIPTIONS)
        )
    )

    sections.append("## Collection pseudo-classes")
    sections.append(
        "Applied after element filtering; they operate on the whole result list "
        "(in document order)."
    )
    sections.append(
        _md_table(
            ["Name", "Aliases", "What it does", "Example"],
            pseudo_rows(POST_PSEUDO_DESCRIPTIONS),
        )
    )

    sections.append("## Relational pseudo-classes")
    sections.append(
        "Take a reference selector as an argument and keep elements positioned "
        "relative to its first match."
    )
    sections.append(
        _md_table(
            ["Name", "Aliases", "What it does", "Example"],
            pseudo_rows(RELATIONAL_PSEUDO_DESCRIPTIONS),
        )
    )

    sections.append("## Parser-level pseudo-classes")
    sections.append(
        "Handled by the selector parser/executor itself rather than the clause registry."
    )
    sections.append(
        _md_table(
            ["Name", "Aliases", "What it does", "Example"],
            pseudo_rows(PARSER_PSEUDO_DESCRIPTIONS),
        )
    )

    sections.append("## Attribute operators")
    sections.append(
        "Applied in brackets, e.g. `text[size>12]`. Attribute names use CSS-style "
        "hyphens or Python-style underscores interchangeably."
    )
    op_rows: List[Tuple[str, str, str, str]] = [
        (
            ATTRIBUTE_EXISTS_ROW[0],
            ATTRIBUTE_EXISTS_ROW[1],
            ATTRIBUTE_EXISTS_ROW[2],
            _code(ATTRIBUTE_EXISTS_ROW[3]),
        )
    ]
    for op in sorted(ATTRIBUTE_OP_DESCRIPTIONS):
        desc, example = ATTRIBUTE_OP_DESCRIPTIONS[op]
        op_rows.append((_code(op), "", desc, _code(example)))
    sections.append(_md_table(["Operator", "Aliases", "Meaning", "Example"], op_rows))

    if attribute_handler_names:
        sections.append("## Registered attribute handlers")
        handler_rows = []
        for name in sorted(ATTRIBUTE_HANDLER_DESCRIPTIONS):
            desc, example = ATTRIBUTE_HANDLER_DESCRIPTIONS[name]
            handler_rows.append((_code(name), "", desc, _code(example)))
        sections.append(_md_table(["Name", "Aliases", "What it does", "Example"], handler_rows))

    sections.append("## Extending the vocabulary")
    sections.append(
        "Third-party packages can add clauses with `natural_pdf.selectors.register_pseudo`, "
        "`register_attribute`, `register_post_pseudo`, and `register_relational_pseudo`."
    )

    intro = (
        "Every pseudo-class and attribute operator registered in the selector engine. "
        "Generated from `natural_pdf/selectors/registry.py`, "
        "`natural_pdf/selectors/_clauses.py`, and the parser dispatch tables in "
        "`natural_pdf/selectors/parser.py`."
    )
    return _page("Selector Reference", intro, "\n\n".join(sections))


# ---------------------------------------------------------------------------
# Page: engines.md
# ---------------------------------------------------------------------------


def _import_engine_provider_modules() -> None:
    """Import the modules that register built-in engines at import time.

    All registrations are metadata-only (factories are lazy), so this never
    loads models or touches the network.
    """
    import importlib

    for module in (
        "natural_pdf",
        "natural_pdf.classification.classification_provider",
        "natural_pdf.checkbox.checkbox_manager",
        "natural_pdf.deskew.deskew_provider",
        "natural_pdf.guides.guides_provider",
        "natural_pdf.layout.layout_manager",
        "natural_pdf.ocr.ocr_provider",
        "natural_pdf.selectors.selector_provider",
        "natural_pdf.tables.structure_provider",
        "natural_pdf.tables.table_provider",
    ):
        importlib.import_module(module)


def _manager_specs() -> Dict[str, Any]:
    """Return EngineManagerSpec objects keyed by capability, where available."""
    import importlib

    specs: Dict[str, Any] = {}
    for module_name in (
        "natural_pdf.layout.layout_manager",
        "natural_pdf.checkbox.checkbox_manager",
    ):
        module = importlib.import_module(module_name)
        spec = getattr(module, "_MANAGER", None)
        if spec is not None:
            specs[spec.capability] = spec
    return specs


def _optional_dep_hint_for(install_hint: Optional[str]) -> Optional[str]:
    """Expand a bare pip hint to the optional_imports hints when they match."""
    if not install_hint:
        return None
    from natural_pdf.utils.optional_imports import OPTIONAL_DEPENDENCIES

    for dep in OPTIONAL_DEPENDENCIES.values():
        if install_hint in dep.install_hints:
            return " or ".join(dep.install_hints)
    return install_hint


def generate_engines_page() -> str:
    _import_engine_provider_modules()

    from natural_pdf.engine_provider import get_provider
    from natural_pdf.engine_registry import list_engines
    from natural_pdf.ocr import unified_dispatch

    provider = get_provider()
    specs = _manager_specs()
    unified = unified_dispatch.list_engines()

    all_engines = list_engines()

    def rows_for(capability: str) -> List[Tuple[str, str, str]]:
        spec = specs.get(capability)
        rows = []
        for name in sorted(all_engines.get(capability, ())):
            metadata = provider.get_metadata(capability, name) or {}
            notes: List[str] = []

            if spec is not None and name in spec.deprecated_aliases:
                notes.append(f"deprecated alias for `{spec.deprecated_aliases[name]}`")
            options_class = metadata.get("options_class")
            if options_class is not None and options_class is not type(None):
                notes.append(f"options: `{options_class.__name__}`")
            for key in sorted(metadata):
                if key in {"options_class", "class_factory", "install_hint"}:
                    continue
                value = metadata[key]
                if isinstance(value, (str, int, float, bool)):
                    notes.append(f"{key}: {value}")

            install = None
            if capability.startswith("ocr") and name in unified:
                install = unified[name].install_hint
            if install is None and spec is not None:
                install = spec.install_hints.get(name)
            if install is None:
                install = metadata.get("install_hint")
            install = _optional_dep_hint_for(install)

            rows.append((_code(name), install or "included", "; ".join(notes) or ""))
        return rows

    # Group capabilities that expose identical engine tables (e.g. the ocr trio).
    by_rows: Dict[Tuple[Tuple[str, str, str], ...], List[str]] = {}
    for capability in sorted(all_engines):
        key = tuple(rows_for(capability))
        by_rows.setdefault(key, []).append(capability)

    sections: List[str] = []
    for rows, capabilities in sorted(by_rows.items(), key=lambda item: item[1][0]):
        title = _code(capabilities[0])
        if len(capabilities) > 1:
            title += " (also " + ", ".join(_code(c) for c in capabilities[1:]) + ")"
        sections.append(f"## Capability: {title}")
        sections.append(_md_table(["Engine", "Requires", "Notes"], rows))

    # Unified OCR dispatch registry (includes VLM shorthands not registered
    # as provider engines).
    sections.append("## OCR dispatch registry")
    sections.append(
        "The unified OCR registry behind `page.apply_ocr(engine=...)`. Named VLM-family "
        "entries resolve to local vision-language models instead of classic OCR engines; "
        "the generic `vlm` entry can use either a local model or a configured remote client."
    )
    ocr_rows = []
    for name in sorted(unified):
        entry = unified[name]
        details: List[str] = []
        if entry.vlm_family:
            details.append(f"VLM family: {entry.vlm_family}")
        if entry.options_class is not None:
            details.append(f"options: `{entry.options_class.__name__}`")
        install = _optional_dep_hint_for(entry.install_hint)
        ocr_rows.append(
            (_code(name), entry.engine_type, install or "included", "; ".join(details) or "")
        )
    sections.append(_md_table(["Engine", "Type", "Requires", "Notes"], ocr_rows))

    intro = (
        "Engines registered per capability in the engine registry "
        '(`natural_pdf.engine_registry.list_engines`). "Requires" shows the install '
        'hint carried by the registration metadata; "included" means the '
        "registration declares no extra install requirement (availability may still "
        "depend on optional packages — run `npdf doctor` to check your environment).\n\n"
        "This page lists the built-in engines only. Third-party plugins registered "
        "through the `natural_pdf.engines` entry point extend these lists at runtime "
        "in your environment; they are deliberately not part of the generated "
        "reference."
    )
    return _page("Engine Reference", intro, "\n\n".join(sections))


# ---------------------------------------------------------------------------
# Page: installation-extras.md
# ---------------------------------------------------------------------------


def generate_installation_extras_page() -> str:
    from natural_pdf.utils import optional_imports

    deps = optional_imports.OPTIONAL_DEPENDENCIES
    groups = optional_imports.OPTIONAL_DEPENDENCY_GROUPS

    default_applicable = optional_imports.OptionalDependency.__dataclass_fields__[
        "applicable"
    ].default

    def dep_rows(names: Iterable[str]) -> List[Tuple[str, str, str, str]]:
        rows = []
        for name in names:
            dep = deps[name]
            packages = ", ".join(_code(p) for p in (dep.package_names or (dep.module_name,)))
            desc = dep.description or ""
            if dep.applicable is not default_applicable:
                desc = (
                    desc + " " if desc else ""
                ) + "(Platform-conditional: `npdf doctor` shows N/A where it does not apply.)"
            hints = " or ".join(_code(h) for h in dep.install_hints)
            rows.append((_code(name), packages, desc, hints))
        return rows

    sections: List[str] = []
    for group in sorted(groups):
        sections.append(f"## `natural-pdf[{group}]`")
        sections.append(f'Install: `pip install "natural-pdf[{group}]"`')
        sections.append(
            _md_table(
                ["Dependency", "Packages", "What it enables", "Install on its own"],
                dep_rows(groups[group]),
            )
        )

    grouped = {name for members in groups.values() for name in members}
    ungrouped = sorted(set(deps) - grouped)
    if ungrouped:
        sections.append("## Not in any extra")
        sections.append("These optional dependencies are opt-in: install them individually.")
        sections.append(
            _md_table(
                ["Dependency", "Packages", "What it enables", "Install on its own"],
                dep_rows(ungrouped),
            )
        )

    intro = (
        "The optional dependency matrix from `natural_pdf.utils.optional_imports` — "
        "the same data `npdf doctor` reports for your environment. Each extra is a "
        "pip install target; each row is one optional dependency the library probes "
        "for at runtime."
    )
    return _page("Installation Extras", intro, "\n\n".join(sections))


# ---------------------------------------------------------------------------
# Page: exceptions.md
# ---------------------------------------------------------------------------


def generate_exceptions_page() -> str:
    import natural_pdf.exceptions as exc_module

    module_name = exc_module.__name__
    classes = {
        name: obj
        for name, obj in vars(exc_module).items()
        if inspect.isclass(obj) and issubclass(obj, BaseException) and obj.__module__ == module_name
    }

    children: Dict[str, List[str]] = {name: [] for name in classes}
    roots: List[str] = []
    for name, obj in classes.items():
        in_module_bases = [b.__name__ for b in obj.__bases__ if b.__name__ in classes]
        if in_module_bases:
            children[in_module_bases[0]].append(name)
        else:
            roots.append(name)

    def first_doc_line(obj: type) -> str:
        doc = inspect.getdoc(obj) or ""
        return doc.splitlines()[0].strip() if doc else ""

    lines: List[str] = []

    def render(name: str, depth: int) -> None:
        obj = classes[name]
        base = obj.__bases__[0].__name__
        suffix = f" — {first_doc_line(obj)}" if first_doc_line(obj) else ""
        if depth == 0:
            lines.append(f"- `{name}({base})`{suffix}")
        else:
            lines.append("    " * depth + f"- `{name}`{suffix}")
        for child in sorted(children[name]):
            render(child, depth + 1)

    for root in sorted(roots):
        render(root, 0)

    body = "\n".join(lines)
    body += (
        "\n\nCatch `NaturalPDFError` to handle every library-raised error with one "
        "handler:\n\n"
        "```python\n"
        "from natural_pdf.exceptions import NaturalPDFError\n\n"
        "try:\n"
        "    pdf.apply_ocr()\n"
        "except NaturalPDFError as e:\n"
        "    handle_error(e)\n"
        "```"
    )

    intro = (
        "The exception hierarchy defined in `natural_pdf/exceptions.py`, introspected "
        "from the module. Indentation shows inheritance."
    )
    return _page("Exception Reference", intro, body)


# ---------------------------------------------------------------------------
# Page: ocr-options.md
# ---------------------------------------------------------------------------


def _collect_field_docs(module: Any) -> Tuple[Dict[str, Dict[str, str]], Dict[str, Dict[str, str]]]:
    """Extract per-field descriptions and annotation text from a module via ast.

    For each dataclass field, prefer the PEP 258-style attribute docstring (a
    string literal directly after the assignment); fall back to a trailing
    ``#`` comment on the same source line. Missing descriptions are omitted.
    Returns ``(docs, annotations)``, both keyed by class name then field name.
    """
    source = inspect.getsource(module)
    source_lines = source.splitlines()
    tree = ast.parse(source)

    docs: Dict[str, Dict[str, str]] = {}
    annotations: Dict[str, Dict[str, str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        class_docs: Dict[str, str] = {}
        class_annotations: Dict[str, str] = {}
        body = node.body
        for index, stmt in enumerate(body):
            if not isinstance(stmt, ast.AnnAssign) or not isinstance(stmt.target, ast.Name):
                continue
            field_name = stmt.target.id
            class_annotations[field_name] = ast.unparse(stmt.annotation)
            description = ""
            # Attribute docstring: string literal expression right after the field.
            if index + 1 < len(body):
                nxt = body[index + 1]
                if (
                    isinstance(nxt, ast.Expr)
                    and isinstance(nxt.value, ast.Constant)
                    and isinstance(nxt.value.value, str)
                ):
                    description = " ".join(nxt.value.value.split())
            if not description:
                # Trailing comment on the same line.
                line = source_lines[stmt.lineno - 1]
                if "#" in line:
                    description = line.split("#", 1)[1].strip()
            if description:
                class_docs[field_name] = description
        docs[node.name] = class_docs
        annotations[node.name] = class_annotations
    return docs, annotations


def generate_ocr_options_page() -> str:
    from natural_pdf.ocr import ocr_options as options_module
    from natural_pdf.ocr import unified_dispatch

    base = options_module.BaseOCROptions
    classes = [
        obj
        for obj in vars(options_module).values()
        if inspect.isclass(obj)
        and issubclass(obj, base)
        and obj.__module__ == options_module.__name__
        and dataclasses.is_dataclass(obj)
    ]
    ordered = [base] + sorted((c for c in classes if c is not base), key=lambda c: c.__name__)

    field_docs, field_annotations = _collect_field_docs(options_module)

    engines_by_options: Dict[str, List[str]] = {}
    engines_without_options: List[str] = []
    for name, entry in sorted(unified_dispatch.list_engines().items()):
        if entry.options_class is not None:
            engines_by_options.setdefault(entry.options_class.__name__, []).append(name)
        else:
            engines_without_options.append(name)

    def default_repr(f: dataclasses.Field) -> str:
        if f.default is not dataclasses.MISSING:
            return repr(f.default)
        if f.default_factory is not dataclasses.MISSING:  # type: ignore[misc]
            try:
                return repr(f.default_factory())
            except Exception:
                return f.default_factory.__name__
        return "(required)"

    def annotation_text(cls: type, f: dataclasses.Field) -> str:
        from_source = field_annotations.get(cls.__name__, {}).get(f.name)
        if from_source:
            return from_source
        annotation = f.type
        if isinstance(annotation, str):
            return annotation
        return str(annotation).replace("typing.", "")

    sections: List[str] = []
    for cls in ordered:
        own_fields = [
            f for f in dataclasses.fields(cls) if f.name in cls.__dict__.get("__annotations__", {})
        ]
        title = f"## `{cls.__name__}`"
        if cls is base:
            title += " (shared)"
        sections.append(title)

        used_by = engines_by_options.get(cls.__name__)
        meta_lines: List[str] = []
        doc = inspect.getdoc(cls) or ""
        if doc:
            meta_lines.append(" ".join(doc.split()))
        if used_by:
            meta_lines.append("Used by engine(s): " + ", ".join(_code(n) for n in used_by) + ".")
        elif cls is base:
            meta_lines.append(
                "Fields shared by every engine's options class. `extra_args` is passed "
                "through to the underlying engine."
            )
        if meta_lines:
            sections.append("\n\n".join(meta_lines))

        if not own_fields:
            sections.append("No options beyond the shared `BaseOCROptions` fields.")
            continue

        rows = []
        for f in own_fields:
            rows.append(
                (
                    _code(f.name),
                    _code(annotation_text(cls, f)),
                    _code(default_repr(f)),
                    field_docs.get(cls.__name__, {}).get(f.name, ""),
                )
            )
        sections.append(_md_table(["Option", "Type", "Default", "Description"], rows))

    if engines_without_options:
        sections.append("## Engines without a typed options class")
        sections.append(
            ", ".join(_code(n) for n in sorted(engines_without_options))
            + " — configure these through `apply_ocr()` keyword arguments (e.g. `model=`) "
            "instead of an options dataclass."
        )

    intro = (
        "Typed option dataclasses from `natural_pdf/ocr/ocr_options.py`. Pass an "
        'instance via `page.apply_ocr(engine="...", options=...)`. Subclass tables '
        "list only the fields each class adds; every class also accepts the shared "
        "`BaseOCROptions` fields."
    )
    return _page("OCR Options Reference", intro, "\n\n".join(sections))


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

PAGES: Dict[str, Callable[[], str]] = {
    "selectors.md": generate_selectors_page,
    "engines.md": generate_engines_page,
    "installation-extras.md": generate_installation_extras_page,
    "exceptions.md": generate_exceptions_page,
    "ocr-options.md": generate_ocr_options_page,
}


def build_all_pages() -> Dict[str, str]:
    """Introspect the registries in THIS process and render every page.

    Only safe when the current interpreter is pristine (nothing has mutated
    the global registries). ``main()`` never calls this directly for output —
    it goes through :func:`build_all_pages_isolated` instead.
    """
    return {name: generator() for name, generator in sorted(PAGES.items())}


ENGINE_ENTRY_POINT_GROUP = "natural_pdf.engines"  # EngineProvider.ENTRY_POINT_GROUP


def _suppress_engine_entry_point_plugins() -> None:
    """Hide third-party ``natural_pdf.engines`` plugins from introspection.

    Policy: the generated reference documents built-in engines only, so the
    drift gate cannot flap depending on which plugins happen to be installed.
    ``EngineProvider._ensure_entry_points_loaded`` runs unconditionally at
    ``natural_pdf.engine_provider`` import time and has no opt-out flag, so
    this must patch ``importlib.metadata.entry_points`` BEFORE natural_pdf is
    imported. Only meaningful in the ``--introspect-json`` subprocess, which
    starts from a clean interpreter.
    """
    import importlib.metadata as importlib_metadata

    real_entry_points = importlib_metadata.entry_points

    class _FilteredEntryPoints:
        """Proxy that empties the engine plugin group for both lookup styles."""

        def __init__(self, wrapped: Any) -> None:
            self._wrapped = wrapped

        def select(self, **params: Any) -> Any:  # importlib.metadata >= 3.10
            if params.get("group") == ENGINE_ENTRY_POINT_GROUP:
                return ()
            return self._wrapped.select(**params)

        def get(self, group: str, default: Any = None) -> Any:  # legacy mapping API
            if group == ENGINE_ENTRY_POINT_GROUP:
                return () if default is None else default
            getter = getattr(self._wrapped, "get", None)
            return getter(group, default) if callable(getter) else default

        def __iter__(self) -> Any:
            return iter(self._wrapped)

        def __getattr__(self, name: str) -> Any:
            return getattr(self._wrapped, name)

    def filtered_entry_points(**params: Any) -> Any:
        if params.get("group") == ENGINE_ENTRY_POINT_GROUP:
            return ()
        return _FilteredEntryPoints(real_entry_points(**params))

    importlib_metadata.entry_points = filtered_entry_points


def build_all_pages_isolated() -> Dict[str, str]:
    """Run all registry introspection in a fresh interpreter and return pages.

    The registries this script reads (selector clauses, engine provider,
    unified OCR dispatch) are mutable process globals: test suites register
    throwaway engines, and installed plugins self-register on import. A fresh
    ``sys.executable`` subprocess (``--introspect-json``) guarantees the pages
    reflect a clean ``import natural_pdf`` regardless of what already ran in
    the calling process.
    """
    with tempfile.TemporaryDirectory() as tmp:
        out_path = Path(tmp) / "pages.json"
        try:
            proc = subprocess.run(
                [
                    sys.executable,
                    str(Path(__file__).resolve()),
                    "--introspect-json",
                    str(out_path),
                ],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                timeout=INTROSPECTION_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired as exc:
            raise ReferenceGenerationError(
                "introspection subprocess timed out after "
                f"{INTROSPECTION_TIMEOUT_SECONDS} seconds"
            ) from exc
        if proc.returncode != 0:
            raise ReferenceGenerationError(
                "introspection subprocess failed:\n" + (proc.stderr.strip() or proc.stdout.strip())
            )
        pages = json.loads(out_path.read_text(encoding="utf-8"))
    if sorted(pages) != sorted(PAGES):
        raise ReferenceGenerationError(
            f"introspection subprocess returned pages {sorted(pages)}, " f"expected {sorted(PAGES)}"
        )
    return pages


def find_orphaned_pages(output_dir: Path, expected_names: Iterable[str]) -> List[Path]:
    """Markdown files in ``output_dir`` that carry the GENERATED header but are
    no longer in the expected page set — leftovers from pages this script used
    to generate. Hand-written pages (no header) are never returned: the header
    namespace belongs to this generator, everything else is off limits."""
    expected = set(expected_names)
    orphans: List[Path] = []
    if not output_dir.is_dir():
        return orphans
    for path in sorted(output_dir.glob("*.md")):
        if path.name in expected:
            continue
        try:
            content = path.read_text(encoding="utf-8")
        except OSError:
            continue
        if content.startswith(HEADER_COMMENT):
            orphans.append(path)
    return orphans


def main(argv: Optional[Sequence[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help=(
            "Regenerate in memory and exit nonzero if the committed pages "
            "differ or an orphaned generated page lingers in the output dir."
        ),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--introspect-json",
        type=Path,
        metavar="PATH",
        help=(
            "Internal: introspect the registries in this (clean) interpreter, "
            "write {page: markdown} JSON to PATH, and exit. Suppresses "
            "third-party engine entry-point plugins."
        ),
    )
    args = parser.parse_args(argv)

    if args.introspect_json is not None:
        _suppress_engine_entry_point_plugins()
        pages = build_all_pages()
        args.introspect_json.write_text(json.dumps(pages), encoding="utf-8")
        return 0

    pages = build_all_pages_isolated()

    if args.check:
        stale: List[str] = []
        for name, content in pages.items():
            path = args.output / name
            if not path.exists():
                stale.append(f"{path}: missing")
            elif path.read_text(encoding="utf-8") != content:
                stale.append(f"{path}: out of date")
        for orphan in find_orphaned_pages(args.output, pages):
            stale.append(
                f"{orphan}: orphaned generated page (bears the GENERATED header "
                "but is no longer generated)"
            )
        if stale:
            for line in stale:
                print(line, file=sys.stderr)
            print(
                "Reference pages are out of date. Regenerate with: "
                "uv run python scripts/generate_reference.py",
                file=sys.stderr,
            )
            return 1
        print(f"{len(pages)} reference pages up to date in {args.output}")
        return 0

    args.output.mkdir(parents=True, exist_ok=True)
    for name, content in pages.items():
        path = args.output / name
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path} ({len(content.splitlines())} lines)")
    # Generation owns the GENERATED-header namespace: pages this script no
    # longer produces are deleted so they cannot linger on the site forever.
    for orphan in find_orphaned_pages(args.output, pages):
        orphan.unlink()
        print(f"removed orphaned generated page {orphan}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
