name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  tests:
    name: nox (${{ matrix.os }} | py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.10', '3.11']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip & nox virtualenvs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.nox
          key: ${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles('pyproject.toml', 'noxfile.py') }}
          restore-keys: |
            ${{ runner.os }}-py${{ matrix.python }}-

      - name: Install Nox and uv
        run: |
          python -m pip install --upgrade pip
          pip install nox uv

      - name: Run Nox sessions
        env:
          NOTEBOOK_WORKERS: 3
        run: |
          # Run linting, the full test suite, and the tutorials
          nox --non-interactive -s lint test_full tutorials

      - name: Run Nox sessions
        run: |
          # Run linting and full test suite (includes optional dependencies)
          nox --non-interactive -s lint test_full
